language: generic
branches:
  only:
  - master
cache:
  directories:
  - vendor
services:
- docker
sudo: required
install:
- make bootstrap
script:
- make build test dist
deploy:
  provider: gcs
  access_key_id:
    secure: "Ar0qQC4yxxPAJ/pgYewqa+JqbZ/cdrUmHb2XBXZys6p6MoyZxofpRziT7MaeFSamoGKT32fGDO0X186uiu2o8K6WvHFNj90Z5Hzy+lqzOyuC7k24s5yIJo7kgKbzzqylKpbwdCUK4dtlnT+ls2wu7596bf8UTuhyFUZwXclgk+ymIrIEdDdbxITio8eEjjbjGdN1We8r2oV9uy/smbG/BEkyHLeCzyZnqQ3Ysz5UbW6dusdeA8YVpbv9HC6J1j/5zF1jwAtS/ZRli6x9ONBZjTd+fZvzFkWEeJRxTUxw4Y7bcuxT/voW6u4iW+3mwNzrkTwHEKHnaLTRgsp8y4WE8U/8BPOS59JO+TcQDXhXXss/6mu6PGhZLaUF2wxyNNCQR6e5+OgxzZAhARsIm0nDwOkZCg52fxO7MOBk2ZHhh3jR0J/tW9I0BO4PlAArh02RE/EYfi6M8C/UhImwadZ0bS0Ndk3Gr9zYI+MKxgIZk2vw1MdTbx1vpLZk6xHHSBwfsc2Ny4lm0Bqxae+KpQKkcexsX5I2RUs8xGoKqJl9mdthPgyH46og2vlnuPCc6z3sIpz5NemIDIcu817GxcIgNnyTlxiTdnM27HZKdPln1pjHzvQw1drFZ/tzlwU3BmWZni0DMqWPBngeXaZm+XgEcuTcQ8S6Q2QtgR1k+NSd9cQ="
  secret_access_key:
    secure: "E0YPcsgawTyx2NHvIkJeSYfTM3U4nuGbGftIGUbkLUHGrgX3aU541Phj6nEbqXJMRKKRxffjeayPrsFZUnRBctW32oNtV5eI6KPl/292qRy68MMgtj1F8ZFL5O9iA6D6vEe5s9k63hym09OiQqFZHsPpTtkNi2CcA7NqHSqJwpxXYl035gcfXhtbUzFnggC4/pDCjHzHa7ENWSHkin6MuOLthRb4UVaJuM9RBKUxYPJa4yece4oTrMWsNTFjsk2SrSUb+pDUP7SLRn1m3IgzD6NCVco36HaRPzPI74l72U7nO5a9/y5/9tqPocr5MbkbCS7Qd77JIANsb8MjS/O2m4um8jIjuwNndNFv6ualogSVHg50JbrOaG/SKn1i1B7dwmlzCVRYRAUgTb9o2rTDKPVxETdMSxkujm3sGVLw27N9VEDL/3Q9lgL/GDmV2dlV3BkWwunQplYtKoTp3ax2U4H5j1Fdux6KLQPyjb4b+wpmFl6P63zgqmTCes6nEt3Wl/3Aig6ICvRnQqAkMD0BYRtVUtkfmx19YgAdGDq8l5h8PGGJ+lLb2NDGEEYqPASSlIDMrohP5vPSDW8cb0z223Q4GswOdIAewNfAwuxb8okHzLFeJ0OiwzSvIhZY7XgccE25Y0xM8mqDYlZf6krNrVV0GezFLxnf2g8uO2j7TNU="
  bucket: object-storage-cli
  local-dir: _dist
  on:
    branch: master
  acl: public-read
